server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      database: xc-cms
      uri: mongodb://127.0.0.1:27017
  rabbitmq:
    host: 120.79.93.16
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
weifuwukt:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1	#此routingKey为门户站点ID
